name: Publish package to GitHub Packages
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
     
      - name: package.json info
        id: info
        uses: jaywcjlove/github-action-package@main
        with:
          rename: '@mastashake08/shake-video-editor'

      - run: echo "name - ${{ steps.info.outputs.name }}"
      - run: echo "version - ${{ steps.info.outputs.version }}"
      
      # Setup .npmrc file to publish to GitHub Packages
    
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@mastashake08'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}